"""
Pragma Code Generator — C target
Walks the AST and emits C99 source code.

Methods:
  generate(program: Program, safe: bool = False) -> str
"""

from typing import List, Any, Optional
from ast_nodes import *


# ── Type map ───────────────────────────────────────────────────────────────────

_TYPE_MAP = {
    'int':        'int',       'integer':    'int',
    'int8':       'int8_t',    'integer8':   'int8_t',
    'int16':      'int16_t',   'integer16':  'int16_t',
    'int32':      'int32_t',   'integer32':  'int32_t',
    'int64':      'int64_t',   'integer64':  'int64_t',
    'uint':       'uint32_t',
    'uint8':      'uint8_t',
    'uint16':     'uint16_t',
    'uint32':     'uint32_t',
    'uint64':     'uint64_t',
    'double':     'double',
    'float':      'double',
    'string':     'char*',
    'String':     'char*',
    'bool':       'bool',
    'void':       'void',
    'char':       'char',
    'none':       'void',      # none <p> → void*
}

def _ct(name: str) -> str:
    """Map a Pragma type name to its C equivalent."""
    if name in _TYPE_MAP:
        return _TYPE_MAP[name]
    # Pointer types: <X>, <<X>>, etc.
    if name.startswith('<') and name.endswith('>'):
        levels = 0
        inner = name
        while inner.startswith('<') and inner.endswith('>'):
            levels += 1
            inner = inner[1:-1]
        return _ct(inner) + '*' * levels
    # array[X] → X*  (decays to pointer)
    if name.startswith('array[') and name.endswith(']'):
        inner = name[6:-1]
        return f'{_ct(inner)}*'
    if name.startswith('chararray_'):
        return 'char*'
    return name   # user-defined type — pass through


def _is_chararray(type_name: str) -> tuple:
    if type_name.startswith('chararray_'):
        return True, type_name[len('chararray_'):]
    return False, 0


# ── Preambles ─────────────────────────────────────────────────────────────────

_SAFE_PREAMBLE = """\
#include <assert.h>

#define pragma_safe_index(arr, idx, len) __extension__({\
    int __idx = (int)(idx);\
    int __len = (int)(len);\
    if (__idx < 0 || __idx >= __len) {\
        fprintf(stderr, "Pragma bounds error: index %d out of range [0, %d)\\n", __idx, __len);\
        exit(1);\
    }\
    (arr)[__idx];\
})
"""

_PREAMBLE = """\
/* Generated by Pragma — do not edit */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>

#ifdef max
#undef max
#endif
#ifdef min
#undef min
#endif

/* ── Exception runtime ──────────────────────────────────────── */
#define PRAGMA_MAX_TRY_DEPTH 64
static jmp_buf* __pragma_jmp_stack[PRAGMA_MAX_TRY_DEPTH];
static int      __pragma_jmp_depth = 0;
static char*    __pragma_exc_msg   = "";
static int      __pragma_exc_type  = 0;
static void __pragma_throw(int exc_type, const char* msg) {
    if (__pragma_jmp_depth == 0) {
        fprintf(stderr, "Unhandled exception (%d): %s\\n", exc_type, msg);
        exit(1);
    }
    __pragma_exc_type = exc_type;
    __pragma_exc_msg  = (char*)msg;
    longjmp(*__pragma_jmp_stack[--__pragma_jmp_depth], exc_type);
}
/* ─────────────────────────────────────────────────────────────── */

#define pragma_print(x) _Generic((x),              \\
    int:                printf("%d\\n",   x),       \\
    unsigned int:       printf("%u\\n",   x),       \\
    long:               printf("%ld\\n",  x),       \\
    unsigned long:      printf("%lu\\n",  x),       \\
    long long:          printf("%lld\\n", x),       \\
    unsigned long long: printf("%llu\\n", x),       \\
    double:             printf("%g\\n",   x),       \\
    _Bool:              printf("%s\\n",   (x) ? "true" : "false"), \\
    char*:              printf("%s\\n",   x),       \\
    default:            printf("<?>\\n")            \\
)
"""


# ── Code generator ─────────────────────────────────────────────────────────────

class CodeGen:
    """
    Walks the Pragma AST and produces C source.
    Inputs:  program: Program, safe: bool
    Outputs: str  — C source text
    """

    def __init__(self, safe: bool = False):
        self._lines: List[str] = []
        self._depth = 0
        self._safe = safe
        self._current_object: Optional[str] = None
        self._current_parent: Optional[str] = None
        self._symbols: dict = {}
        self._object_fields: dict = {}
        self._try_counter: int = 0
        self._exc_codes: dict = {}          # exc_type_name → int code
        self._maps: dict = {}               # map_name → (key_type, val_type, capacity)
        self._global_defs: List[str] = []   # map helpers accumulated for global scope
        self._chararray_fields: set = set() # field names declared as chararray (char[N])

    def _emit(self, text: str = ''):
        self._lines.append('    ' * self._depth + text)

    def _emit0(self, text: str = ''):
        self._lines.append(text)

    def _push(self): self._depth += 1
    def _pop(self):  self._depth -= 1
    def _blank(self): self._lines.append('')

    def result(self) -> str:
        return '\n'.join(self._lines).rstrip() + '\n'

    def generate(self, prog: Program) -> str:
        self._emit0(_PREAMBLE)
        if self._safe:
            self._emit0(_SAFE_PREAMBLE)
        self._block_body(prog.body)
        # Inject accumulated global defs (map helpers etc.) just before first function
        if self._global_defs:
            insert_at = next(
                (i for i, ln in enumerate(self._lines) if ln.startswith('int main') or ln.endswith(') {')),
                len(self._lines)
            )
            self._lines[insert_at:insert_at] = self._global_defs
        return self.result()

    def _block_body(self, stmts: List[Any]):
        for s in stmts:
            self._stmt(s)

    # ── Statement dispatch ────────────────────────────────────────────────────

    def _stmt(self, node: Any):
        t = type(node)
        dispatch = {
            ImportDecl:    self._s_import,
            VarDecl:       self._s_var,
            ConstantDecl:  self._s_constant,
            ArrayDecl:     self._s_array,
            ListDecl:      self._s_list,
            MapDecl:       self._s_map,
            FunctionDecl:  self._s_func,
            ObjectDecl:    self._s_object,
            InterfaceDecl: self._s_interface,
            FixedDecl:     self._s_fixed,
            VariantDecl:   self._s_variant,
            RaiseStmt:     self._s_raise,
            AssignStmt:    self._s_assign,
            ReturnStmt:    self._s_return,
            PrintStmt:     self._s_print,
            IfStmt:        self._s_if,
            ForStmt:       self._s_for,
            ForEachStmt:   self._s_foreach,
            WhileStmt:     self._s_while,
            TryStmt:       self._s_try,
            MatchStmt:     self._s_match,
            SwitchStmt:    self._s_iterate,
            EscapeStmt:    lambda n: self._emit('break;'),
            ContinueStmt:  lambda n: self._emit('continue;'),
            NewStmt:       self._s_new_stmt,
            MemAccess:     lambda n: self._emit(self._e(n) + ';'),
            DerefExpr:     lambda n: self._emit(self._e(n) + ';'),
            PostfixOp:     self._s_postfix,
            CallExpr:      lambda n: self._emit(self._e(n) + ';'),
            Identifier:    lambda n: self._emit(self._e(n) + ';'),
            CastExpr:      lambda n: self._emit(self._e(n) + ';'),
            IndexExpr:     lambda n: self._emit(self._e(n) + ';'),
            AddressOf:     lambda n: self._emit(self._e(n) + ';'),
        }
        handler = dispatch.get(t)
        if handler:
            handler(node)
        else:
            self._emit(f'/* [unhandled: {t.__name__}] */')

    # ── Statement emitters ────────────────────────────────────────────────────

    def _s_import(self, node: ImportDecl):
        self._emit0(f'#include "{node.module}.h"')

    def _s_var(self, node: VarDecl):
        self._symbols[node.name] = node.type_name
        # Pointer nesting mismatch check:
        # int <p> = address(x) where x is already a pointer needs <<p>>
        if (node.type_name.startswith('<') and node.type_name.endswith('>')
                and isinstance(node.init, AddressOf)
                and isinstance(node.init.target, Identifier)):
            declared_levels = 0
            inner = node.type_name
            while inner.startswith('<') and inner.endswith('>'):
                declared_levels += 1
                inner = inner[1:-1]
            rhs_type = self._symbols.get(node.init.target.name, '')
            rhs_levels = 0
            rhs_inner = rhs_type
            while rhs_inner.startswith('<') and rhs_inner.endswith('>'):
                rhs_levels += 1
                rhs_inner = rhs_inner[1:-1]
            if rhs_levels > 0 and declared_levels != rhs_levels + 1:
                needed = '<' * (rhs_levels + 1) + node.name + '>' * (rhs_levels + 1)
                raise ValueError(
                    f"Pointer nesting mismatch: '{node.init.target.name}' is a "
                    f"{'<' * rhs_levels}{rhs_inner}{'>' * rhs_levels}, so taking its address "
                    f"requires {rhs_levels + 1} level(s). "
                    f"Use '{needed}' instead of '{node.type_name.replace(node.name, node.name)}'."
                )
        is_ca, ca_size = _is_chararray(node.type_name)
        if is_ca:
            self._emit(f'char {node.name}[{ca_size}];')
            self._emit(f'memset({node.name}, 0, {ca_size});')
            return
        # Function pointer: int <p> = compare()  or  none <p> = compare()
        # Detected when: pointer type + init is a no-arg CallExpr with simple Identifier func
        if (node.type_name.startswith('<') and node.type_name.endswith('>')
                and isinstance(node.init, CallExpr)
                and isinstance(node.init.func, Identifier)
                and not node.init.args):
            inner = node.type_name
            while inner.startswith('<') and inner.endswith('>'):
                inner = inner[1:-1]
            ret_ct = _ct(inner)
            func_name = node.init.func.name
            # Cast source function to match declared return type
            self._emit(f'{ret_ct} (*{node.name})() = ({ret_ct}(*)())(void*){func_name};')
            self._symbols[node.name] = node.type_name  # track as function pointer
            return
        ct = _ct(node.type_name)
        if node.init is not None:
            self._emit(f'{ct} {node.name} = {self._e(node.init)};')
        else:
            self._emit(f'{ct} {node.name};')

    def _s_constant(self, node: ConstantDecl):
        ct = _ct(node.type_name)
        self._emit(f'const {ct} {node.name} = {self._e(node.init)};')

    def _s_array(self, node: ArrayDecl):
        """array int[5] name = [a,b,c,d,e]  or  array int[5][3] grid"""
        ct = _ct(node.elem_type)
        if node.dims:
            dim_str = ''.join(f'[{d}]' for d in node.dims)
            if node.init:
                items = ', '.join(self._e(x) for x in node.init)
                self._emit(f'{ct} {node.name}{dim_str} = {{{items}}};')
            else:
                self._emit(f'{ct} {node.name}{dim_str};')
            self._emit(f'int {node.name}_len = {node.dims[0]};')
        else:
            if node.init:
                n = len(node.init)
                items = ', '.join(self._e(x) for x in node.init)
                self._emit(f'{ct} {node.name}[{n}] = {{{items}}};')
                self._emit(f'int {node.name}_len = {n};')
            else:
                self._emit(f'{ct}* {node.name} = NULL;')
                self._emit(f'int {node.name}_len = 0;')

    def _s_list(self, node: ListDecl):
        """list string[3] names — emitted as fixed array + count"""
        ct = _ct(node.elem_type)
        if node.dims:
            dim_str = ''.join(f'[{d}]' for d in node.dims)
            if node.init:
                items = ', '.join(self._e(x) for x in node.init)
                self._emit(f'{ct} {node.name}{dim_str} = {{{items}}};')
            else:
                self._emit(f'{ct} {node.name}{dim_str};')
            self._emit(f'int {node.name}_len = {node.dims[0]};')
        else:
            if node.init:
                n = len(node.init)
                items = ', '.join(self._e(x) for x in node.init)
                self._emit(f'{ct} {node.name}[{n}] = {{{items}}};')
                self._emit(f'int {node.name}_len = {n};')
            else:
                self._emit(f'{ct}* {node.name} = NULL;')
                self._emit(f'int {node.name}_len = 0;')

    def _s_map(self, node: MapDecl):
        """map [string,int][50] name — struct + get/set/has/remove helpers"""
        cap = node.capacity if node.capacity else 64
        kt = _ct(node.key_type)
        vt = _ct(node.val_type)
        n = node.name
        self._maps[n] = (node.key_type, node.val_type, cap)
        # Determine default return value for get()
        defaults = {'int': '0', 'uint': '0', 'double': '0.0', 'float': '0.0',
                    'bool': 'false', 'char': '0', 'string': 'NULL', 'String': 'NULL'}
        default_val = defaults.get(node.val_type, '0')
        # Use strcmp for string keys, == for everything else
        str_key = node.key_type in ('string', 'String', 'char*')
        if str_key:
            key_eq = lambda a, b: f'strcmp({a},{b})==0'
        else:
            key_eq = lambda a, b: f'{a}=={b}'

        # Emit helpers at global scope (accumulated, injected before first function)
        g = self._global_defs
        g.append(f'/* map [{node.key_type},{node.val_type}][{cap}] {n} */')
        g.append(f'typedef struct {{ {kt} _key; {vt} _val; int _used; }} __PragmaMap_{n}_Entry;')
        g.append(f'static __PragmaMap_{n}_Entry __pragma_map_{n}[{cap}];')
        g.append(f'static int {n}_len = 0;')
        # _get
        g.append(f'static {vt} {n}_get({kt} k) {{')
        g.append(f'    for(int i=0;i<{cap};i++) if(__pragma_map_{n}[i]._used && {key_eq("__pragma_map_"+n+"[i]._key","k")}) return __pragma_map_{n}[i]._val;')
        g.append(f'    return ({vt}){default_val};')
        g.append(f'}}')
        # _set
        g.append(f'static void {n}_set({kt} k, {vt} v) {{')
        g.append(f'    for(int i=0;i<{cap};i++) {{ if(__pragma_map_{n}[i]._used && {key_eq("__pragma_map_"+n+"[i]._key","k")}) {{ __pragma_map_{n}[i]._val=v; return; }} }}')
        g.append(f'    if({n}_len<{cap}) {{ __pragma_map_{n}[{n}_len]._key=k; __pragma_map_{n}[{n}_len]._val=v; __pragma_map_{n}[{n}_len]._used=1; {n}_len++; }}')
        g.append(f'}}')
        # _has
        g.append(f'static int {n}_has({kt} k) {{')
        g.append(f'    for(int i=0;i<{cap};i++) if(__pragma_map_{n}[i]._used && {key_eq("__pragma_map_"+n+"[i]._key","k")}) return 1;')
        g.append(f'    return 0;')
        g.append(f'}}')
        # _remove
        g.append(f'static void {n}_remove({kt} k) {{')
        g.append(f'    for(int i=0;i<{cap};i++) if(__pragma_map_{n}[i]._used && {key_eq("__pragma_map_"+n+"[i]._key","k")}) {{ __pragma_map_{n}[i]._used=0; {n}_len--; return; }}')
        g.append(f'}}')
        g.append('')

    def _s_func(self, node: FunctionDecl, self_type: str = '', parent_type: str = ''):
        is_main = (not self_type) and (node.name.lower() == 'main')
        if is_main:
            self._emit0('int main(void) {')
            self._push()
            old_obj, old_par = self._current_object, self._current_parent
            self._current_object = self._current_parent = None
            self._block_body(node.body)
            self._emit('return 0;')
            self._current_object, self._current_parent = old_obj, old_par
            self._pop()
            self._emit0('}')
            self._blank()
            return

        ct_ret = _ct(node.return_type) if node.return_type != 'void' else 'void'
        params = []
        if self_type:
            params.append(f'{self_type}* self')
        for p in node.params:
            params.append(f'{_ct(p.type_name)} {p.name}')
        param_str = ', '.join(params) if params else 'void'
        prefix = f'{self_type}_' if self_type else ''
        self._emit0(f'{ct_ret} {prefix}{node.name}({param_str}) {{')
        self._push()
        old_obj, old_par = self._current_object, self._current_parent
        self._current_object = self_type or None
        self._current_parent = parent_type or None
        for p in node.params:
            self._symbols[p.name] = p.type_name
        if node.body:
            self._block_body(node.body)
        else:
            self._emit('/* interface method — implement in subtype */')
        self._current_object, self._current_parent = old_obj, old_par
        self._pop()
        self._emit0('}')
        self._blank()

    def _s_object(self, node: ObjectDecl):
        """type Node ... end type  →  C struct typedef"""
        self._emit0(f'typedef struct {node.name} {{')
        self._push()
        if node.parent:
            self._emit(f'{node.parent} base;  /* inherits {node.parent} */')
        if node.fields:
            for f in node.fields:
                # Bit field
                if f.bits is not None:
                    ct = _ct(f.type_name)
                    # Use unsigned int for bit fields
                    self._emit(f'unsigned int {f.name} : {f.bits};')
                    continue
                is_ca, ca_size = _is_chararray(f.type_name)
                if is_ca:
                    self._emit(f'char {f.name}[{ca_size}];')
                    continue
                ct = _ct(f.type_name)
                if f.type_name == f'<{node.name}>':
                    ct = f'struct {node.name}*'
                self._emit(f'{ct} {f.name};')
        else:
            self._emit('char _placeholder;')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

        # Constructor
        parent_fields = self._object_fields.get(node.parent, []) if node.parent else []
        all_fields = parent_fields + node.fields
        self._object_fields[node.name] = node.fields
        param_fields = [f for f in all_fields
                        if not f.type_name.startswith('chararray_') and f.bits is None]
        chararray_fields = [f for f in node.fields if f.type_name.startswith('chararray_')]
        if all_fields:
            cparams = ', '.join(f'{_ct(f.type_name)} {f.name}' for f in param_fields)
            param_str = cparams if cparams else 'void'
            self._emit0(f'{node.name} new{node.name}({param_str}) {{')
            self._push()
            self._emit(f'{node.name} __obj;')
            if node.parent and parent_fields:
                base_args = ', '.join(f.name for f in parent_fields
                                      if not f.type_name.startswith('chararray_'))
                self._emit(f'__obj.base = new{node.parent}({base_args});')
            for f in param_fields:
                if f in node.fields:
                    self._emit(f'__obj.{f.name} = {f.name};')
            for f in chararray_fields:
                _, ca_size = _is_chararray(f.type_name)
                self._emit(f'memset(__obj.{f.name}, 0, {ca_size});')
            self._emit('return __obj;')
            self._pop()
            self._emit0('}')
            self._blank()

        for iface in node.ifaces:
            self._emit0(f'/* {node.name} implements {iface} — vtable filled after method defs */')

        for method in node.methods:
            self._s_func(method, self_type=node.name, parent_type=node.parent or '')

    def _s_interface(self, node: InterfaceDecl):
        self._emit0(f'typedef struct {node.name} {{')
        self._push()
        for m in node.methods:
            ct_ret = _ct(m.return_type) if m.return_type != 'void' else 'void'
            param_types = ', '.join(['void*'] + [_ct(p.type_name) for p in m.params])
            self._emit(f'{ct_ret} (*{m.name})({param_types});')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

    def _s_fixed(self, node: FixedDecl):
        """fixed Priority low=1, medium=2 ... → C enum"""
        self._emit0('typedef enum {')
        self._push()
        auto_val = 0
        for i, m in enumerate(node.members):
            val = m.value if m.value is not None else auto_val
            auto_val = val + 1
            comma = ',' if i < len(node.members) - 1 else ''
            self._emit(f'{node.name}_{m.name} = {val}{comma}')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

    def _s_assign(self, node: AssignStmt):
        # Map set: mapName[key] = value  →  mapName_set(key, value);
        if (node.op == '='
                and isinstance(node.target, IndexExpr)
                and isinstance(node.target.array, Identifier)
                and node.target.array.name in self._maps):
            map_name = node.target.array.name
            key = self._e(node.target.index)
            val = self._e(node.value)
            self._emit(f'{map_name}_set({key}, {val});')
            return
        self._emit(f'{self._e(node.target)} {node.op} {self._e(node.value)};')

    def _s_return(self, node: ReturnStmt):
        if node.value is not None:
            self._emit(f'return {self._e(node.value)};')
        else:
            self._emit('return;')

    def _s_print(self, node: PrintStmt):
        val = node.value
        # Chararray element access (e.g. bw.bytes[3]) has type char — cast to int
        # so _Generic selects the int: branch and char* branches don't conflict.
        if (isinstance(val, IndexExpr)
                and isinstance(val.array, FieldAccess)
                and val.array.field in self._chararray_fields):
            expr = self._e(val)
            self._emit(f'printf("%d\\n", (int)(unsigned char)({expr}));')
        else:
            self._emit(f'pragma_print({self._e(val)});')

    def _s_if(self, node: IfStmt):
        self._emit(f'if ({self._e(node.condition)}) {{')
        self._push()
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')
        for ec in node.elif_clauses:
            self._emit(f'else if ({self._e(ec.condition)}) {{')
            self._push()
            self._block_body(ec.body) if ec.body else self._emit('/* empty */')
            self._pop()
            self._emit('}')
        if node.else_body is not None:
            self._emit('else {')
            self._push()
            self._block_body(node.else_body) if node.else_body else self._emit('/* empty */')
            self._pop()
            self._emit('}')

    def _s_for(self, node: ForStmt):
        if node.c_style or isinstance(node.init, AssignStmt):
            init_str = f'{self._e(node.init.target)} = {self._e(node.init.value)}'
            var_name = (node.init.target.name
                        if isinstance(node.init.target, Identifier) else '?')
        else:
            init = node.init
            ct = _ct(init.type_name)
            start = self._e(init.init) if init.init else '0'
            init_str = f'{ct} {init.name} = {start}'
            var_name = init.name
        cond = self._e(node.condition)
        step = self._step_c(node.step, var_name)
        self._emit(f'for ({init_str}; {cond}; {step}) {{')
        self._push()
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')

    def _step_c(self, step: Any, loop_var: str) -> str:
        if isinstance(step, PostfixOp):
            return f'{self._e(step.operand)}{step.op}'
        if isinstance(step, AssignStmt):
            return f'{self._e(step.target)} {step.op} {self._e(step.value)}'
        return self._e(step)

    def _s_foreach(self, node: ForEachStmt):
        arr = self._e(node.iterable)
        len_expr = f'{arr}_len'
        self._emit(f'for (int __i = 0; __i < {len_expr}; __i++) {{')
        self._push()
        self._emit(f'__auto_type {node.var} = {arr}[__i];')
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')

    def _s_while(self, node: WhileStmt):
        self._emit(f'while ({self._e(node.condition)}) {{')
        self._push()
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')

    def _exc_code(self, name: str) -> int:
        if name not in self._exc_codes:
            self._exc_codes[name] = len(self._exc_codes) + 1
        return self._exc_codes[name]

    def _s_try(self, node: TryStmt):
        n = self._try_counter
        self._try_counter += 1
        self._emit('{')
        self._push()
        self._emit(f'jmp_buf __jbuf_{n};')
        self._emit(f'__pragma_jmp_stack[__pragma_jmp_depth++] = &__jbuf_{n};')
        self._emit(f'int __exc_{n} = setjmp(__jbuf_{n});')
        self._emit(f'if (__exc_{n} == 0) {{')
        self._push()
        self._block_body(node.body)
        self._emit('if (__pragma_jmp_depth > 0) __pragma_jmp_depth--;')
        self._pop()
        self._emit('}')
        self._emit('else {')
        self._push()
        self._emit('if (__pragma_jmp_depth > 0) __pragma_jmp_depth--;')
        for i, catch in enumerate(node.catches):
            codes = [self._exc_code(e) for e in catch.exceptions]
            cond = ' || '.join(f'__exc_{n} == {c}' for c in codes)
            kw = 'if' if i == 0 else 'else if'
            self._emit(f'{kw} ({cond}) {{')
            self._push()
            self._emit(f'char* {catch.var} = __pragma_exc_msg;')
            self._block_body(catch.body)
            self._pop()
            self._emit('}')
        if node.catches:
            self._emit(f'else {{')
            self._push()
            self._emit('__pragma_throw(__pragma_exc_type, __pragma_exc_msg);')
            self._pop()
            self._emit('}')
        self._pop()
        self._emit('}')
        self._pop()
        self._emit('}')

    def _s_raise(self, node: RaiseStmt):
        code = self._exc_code(node.exc_type)
        msg = self._e(node.message) if node.message is not None else f'"{node.exc_type}"'
        self._emit(f'__pragma_throw({code}, {msg});')

    def _s_variant(self, node: VariantDecl):
        """variant Packet ... end variant  →  C union typedef"""
        self._emit0(f'typedef union {node.name} {{')
        self._push()
        for f in node.fields:
            is_ca, ca_size = _is_chararray(f.type_name)
            if is_ca:
                self._chararray_fields.add(f.name)
                self._emit(f'char {f.name}[{ca_size}];')
            else:
                ct = _ct(f.type_name)
                self._emit(f'{ct} {f.name};')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

    def _s_match(self, node: MatchStmt):
        """match — no fall-through: auto-inserts break after each case"""
        all_int = all(isinstance(c.value, IntLit) or c.is_default for c in node.cases)
        if all_int:
            self._emit(f'switch ({self._e(node.expr)}) {{')
            self._push()
            for case in node.cases:
                if case.is_default:
                    self._emit('default: {')
                else:
                    self._emit(f'case {self._e(case.value)}: {{')
                self._push()
                self._block_body(case.body)
                if not case.body or not isinstance(case.body[-1], EscapeStmt):
                    self._emit('break;')
                self._pop()
                self._emit('}')
            self._pop()
            self._emit('}')
        else:
            for i, case in enumerate(node.cases):
                if case.is_default:
                    self._emit('else {')
                elif i == 0:
                    val = self._e(case.value)
                    expr = self._e(node.expr)
                    if isinstance(case.value, StringLit):
                        self._emit(f'if (strcmp({expr}, {val}) == 0) {{')
                    else:
                        self._emit(f'if ({expr} == {val}) {{')
                else:
                    val = self._e(case.value)
                    expr = self._e(node.expr)
                    if isinstance(case.value, StringLit):
                        self._emit(f'else if (strcmp({expr}, {val}) == 0) {{')
                    else:
                        self._emit(f'else if ({expr} == {val}) {{')
                self._push()
                self._block_body(case.body)
                self._pop()
                self._emit('}')

    def _s_iterate(self, node: SwitchStmt):
        """iterate — fall-through: no auto-break (user uses escape to stop)"""
        self._emit(f'switch ({self._e(node.expr)}) {{')
        self._push()
        for case in node.cases:
            if case.is_default:
                self._emit('default:')
            else:
                self._emit(f'case {self._e(case.value)}:')
            self._push()
            self._block_body(case.body)
            self._pop()
        self._pop()
        self._emit('}')

    def _s_new_stmt(self, node: NewStmt):
        self._emit(self._e_new(node) + ';')

    def _s_postfix(self, node: PostfixOp):
        sym = '++' if node.op == '++' else '--'
        self._emit(f'{self._e(node.operand)}{sym};')

    # ── Type inference ────────────────────────────────────────────────────────

    def _expr_type(self, node: Any) -> str:
        if isinstance(node, Identifier):
            return self._symbols.get(node.name, '')
        if isinstance(node, FieldAccess):
            obj_type = self._expr_type(node.obj)
            if obj_type.startswith('<') and obj_type.endswith('>'):
                base = obj_type[1:-1]
            else:
                base = obj_type
            for f in self._object_fields.get(base, []):
                if f.name == node.field:
                    return f.type_name
        return ''

    # ── Expression emitter ────────────────────────────────────────────────────

    def _e(self, node: Any) -> str:
        t = type(node)

        if t is Identifier:   return node.name
        if t is IntLit:       return str(node.value)
        if t is FloatLit:
            s = str(node.value)
            return s if '.' in s or 'e' in s else s + '.0'
        if t is StringLit:    return f'"{node.value}"'
        if t is BoolLit:      return 'true' if node.value else 'false'
        if t is NullLit:      return 'NULL'
        if t is EmptyLit:     return 'NULL'

        if t is SuperRef:
            parent = self._current_parent or '__parent__'
            return f'(({parent}*)self)'

        if t is FieldAccess:
            obj = self._e(node.obj)
            if isinstance(node.obj, SuperRef):
                parent = self._current_parent or '__parent__'
                return f'{parent}_{node.field}'
            if isinstance(node.obj, Identifier) and node.obj.name == 'self':
                return f'self->{node.field}'
            obj_type = self._expr_type(node.obj)
            if obj_type.startswith('<'):
                return f'{obj}->{node.field}'
            return f'{obj}.{node.field}'

        if t is CallExpr:
            func = node.func
            if isinstance(func, FieldAccess) and isinstance(func.obj, SuperRef):
                parent = self._current_parent or '__parent__'
                args = ', '.join([f'({parent}*)self'] + [self._e(a) for a in node.args])
                return f'{parent}_{func.field}({args})'
            if isinstance(func, FieldAccess):
                obj_expr = self._e(func.obj)
                obj_name = func.obj.name if isinstance(func.obj, Identifier) else None
                type_name = self._symbols.get(obj_name) if obj_name else None
                prefix = f'{type_name}_' if type_name else ''
                args = ', '.join([f'&{obj_expr}'] + [self._e(a) for a in node.args])
                return f'{prefix}{func.field}({args})'
            fn = self._e(func)
            args = ', '.join(self._e(a) for a in node.args)
            # Function pointer call through void* (none<>): must cast before calling
            if isinstance(func, Identifier):
                sym_type = self._symbols.get(func.name, '')
                if sym_type in ('<none>', 'none'):
                    return f'((int(*)())({fn}))({args})'
            return f'{fn}({args})'

        if t is BinOp:
            op = node.op
            if op == 'and':      op = '&&'
            elif op == 'or':     op = '||'
            elif op == 'delta':  op = '^'
            elif op == 'left':   op = '<<'
            elif op == 'right':  op = '>>'
            elif op == 'both1':  op = '&'
            elif op == 'either1': op = '|'
            elif op == 'both0':
                # NOR: ~(a | b)
                return f'(~({self._e(node.left)} | {self._e(node.right)}))'
            return f'({self._e(node.left)} {op} {self._e(node.right)})'

        if t is UnaryOp:
            op = node.op
            if op == '!':    return f'(!{self._e(node.operand)})'
            if op == 'flip': return f'(~{self._e(node.operand)})'
            return f'({op}{self._e(node.operand)})'

        if t is PostfixOp:
            return f'{self._e(node.operand)}{node.op}'

        if t is IndexExpr:
            arr = self._e(node.array)
            idx = self._e(node.index)
            # Map read: mapName[key]  →  mapName_get(key)
            if isinstance(node.array, Identifier) and node.array.name in self._maps:
                return f'{arr}_get({idx})'
            if self._safe:
                return f'pragma_safe_index({arr}, {idx}, {arr}_len)'
            return f'{arr}[{idx}]'

        if t is CastExpr:
            return f'(({_ct(node.target_type)})({self._e(node.expr)}))'

        if t is NewStmt:     return self._e_new(node)
        if t is SizeOf:      return f'sizeof({_ct(node.type_name)})'
        if t is MemAccess:   return f'(*((volatile uint8_t*)({self._e(node.address)})))'
        if t is DerefExpr:   return f'(*{self._e(node.pointer)})'
        if t is AddressOf:   return f'(&{self._e(node.target)})'

        return f'/* [unhandled expr: {t.__name__}] */'

    def _e_new(self, node: NewStmt) -> str:
        if node.args:
            args = ', '.join(self._e(a) for a in node.args)
            return f'new{node.type_name}({args})'
        return f'({node.type_name}){{0}}'


# ── Public API ─────────────────────────────────────────────────────────────────

def generate(program: Program, safe: bool = False) -> str:
    return CodeGen(safe=safe).generate(program)
