/* Generated by Pragma — do not edit */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/* Undefine Windows min/max macros that clash with user-defined functions */
#ifdef max
#undef max
#endif
#ifdef min
#undef min
#endif

/* pragma_print: type-generic print via C11 _Generic.
   Uses canonical primitive types only — avoids duplicate-typedef errors
   (int32_t==int, int64_t==long long, etc. on most platforms). */
#define pragma_print(x) _Generic((x),              \
    int:                printf("%d\n",   x),       \
    unsigned int:       printf("%u\n",   x),       \
    long:               printf("%ld\n",  x),       \
    unsigned long:      printf("%lu\n",  x),       \
    long long:          printf("%lld\n", x),       \
    unsigned long long: printf("%llu\n", x),       \
    double:             printf("%g\n",   x),       \
    _Bool:              printf("%s\n",   (x) ? "true" : "false"), \
    char*:              printf("%s\n",   x),       \
    default:            printf("<?>\n")            \
)

int main(void) {
    pragma_print("Hello, World!");
    return 0;
}
