/* Generated by Pragma — do not edit */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>

#ifdef max
#undef max
#endif
#ifdef min
#undef min
#endif

/* ── Exception runtime ──────────────────────────────────────── */
#define PRAGMA_MAX_TRY_DEPTH 64
static jmp_buf* __pragma_jmp_stack[PRAGMA_MAX_TRY_DEPTH];
static int      __pragma_jmp_depth = 0;
static char*    __pragma_exc_msg   = "";
static int      __pragma_exc_type  = 0;
static void __pragma_throw(int exc_type, const char* msg) {
    if (__pragma_jmp_depth == 0) {
        fprintf(stderr, "Unhandled exception (%d): %s\n", exc_type, msg);
        exit(1);
    }
    __pragma_exc_type = exc_type;
    __pragma_exc_msg  = (char*)msg;
    longjmp(*__pragma_jmp_stack[--__pragma_jmp_depth], exc_type);
}
/* ─────────────────────────────────────────────────────────────── */

#define pragma_print(x) _Generic((x),              \
    int:                printf("%d\n",   x),       \
    unsigned int:       printf("%u\n",   x),       \
    long:               printf("%ld\n",  x),       \
    unsigned long:      printf("%lu\n",  x),       \
    long long:          printf("%lld\n", x),       \
    unsigned long long: printf("%llu\n", x),       \
    double:             printf("%g\n",   x),       \
    _Bool:              printf("%s\n",   (x) ? "true" : "false"), \
    char*:              printf("%s\n",   x),       \
    default:            printf("<?>\n")            \
)

typedef union Number {
    int i;
    double d;
} Number;

typedef union ByteWord {
    int raw;
    char bytes[4];
} ByteWord;

int add(int a, int b) {
    return (a + b);
}

int sub(int a, int b) {
    return (a - b);
}

int mul(int a, int b) {
    return (a * b);
}

int square(int x) {
    return (x * x);
}

int apply(void* op, int a, int b) {
    return ((int(*)())(op))(a, b);
}

void transform(int* arr, int n, void* fn) {
    for (int i = 0; (i < n); i++) {
        arr[i] = ((int(*)())(fn))(arr[i]);
    }
}

char* season(int month) {
    switch (month) {
        case 12:
        case 1:
        case 2:
            return "winter";
        case 3:
        case 4:
        case 5:
            return "spring";
        case 6:
        case 7:
        case 8:
            return "summer";
        case 9:
        case 10:
        case 11:
            return "autumn";
        default:
            return "unknown";
    }
}

int grade(int score) {
    switch ((score / 10)) {
        case 10:
        case 9:
            return 1;
        case 8:
            return 2;
        case 7:
            return 3;
        case 6:
            return 4;
        default:
            return 5;
    }
}

int main(void) {
    Number n;
    n.i = 42;
    pragma_print(n.i);
    n.d = 3.14;
    pragma_print(n.d);
    ByteWord bw;
    bw.raw = 16909060;
    pragma_print(bw.bytes[3]);
    pragma_print(bw.bytes[2]);
    pragma_print(apply(add, 10, 3));
    pragma_print(apply(sub, 10, 3));
    pragma_print(apply(mul, 10, 3));
    void (*fp)() = (void(*)())(void*)square;
    pragma_print(((int(*)())(fp))(7));
    int arr[4] = {1, 2, 3, 4};
    int arr_len = 4;
    transform(arr, 4, square);
    for (int i = 0; (i < 4); i++) {
        pragma_print(arr[i]);
    }
    pragma_print(season(1));
    pragma_print(season(7));
    pragma_print(season(10));
    pragma_print(grade(95));
    pragma_print(grade(83));
    pragma_print(grade(55));
    return 0;
    return 0;
}
